apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ug3cltc4l-python 
  janus-idp.io/tekton: ug3cltc4l-python
  backstage.io/kubernetes-id: ug3cltc4l-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ug3cltc4l-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml